### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [OnionShare/OnionShare Desktop](https://hosted.weblate.org/projects/onionshare/translations/).

It also includes following components:

* [OnionShare/Doc - Features](https://hosted.weblate.org/projects/onionshare/doc-features/)

* [OnionShare/Doc - Index](https://hosted.weblate.org/projects/onionshare/doc-index/)

* [OnionShare/Doc - Develop](https://hosted.weblate.org/projects/onionshare/doc-develop/)

* [OnionShare/Doc - Help](https://hosted.weblate.org/projects/onionshare/doc-help/)

* [OnionShare/Doc - Sphinx](https://hosted.weblate.org/projects/onionshare/doc-sphinx/)

* [OnionShare/Doc - Security](https://hosted.weblate.org/projects/onionshare/doc-security/)

* [OnionShare/Doc - Tor](https://hosted.weblate.org/projects/onionshare/doc-tor/)

* [OnionShare/Doc - Install](https://hosted.weblate.org/projects/onionshare/doc-install/)

* [OnionShare/Doc - Advanced](https://hosted.weblate.org/projects/onionshare/doc-advanced/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by emmapeel2** [comment]
Looking at the failure, I see it is trying to take a library from the old Tor Project git repository, that has been moved now. 
See https://github.com/onionshare/onionshare/actions/runs/8926154194/job/24516536080?pr=1902#step:6:48 :

```
fatal: unable to update url base from redirection:
  asked for: https://git.torproject.org/pluggable-transports/goptlib/info/refs?service=git-upload-pack
   redirect: https://gitlab.torproject.org/tpo/team
Failed to download sources: module obfs4proxy: Child process exited with code 128
```
I think the new location of this repository is https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/goptlib 
So the link should be https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/goptlib/info/refs?service=git-upload-pack

**Comment by SaptakS** [comment]
This is blocked on me. I will try to get the build CIs fixed by end of this week.

**Comment by emmapeel2** [comment]
Could you have a look at how to merge this? It has lots of updates and maybe we could even add more translations to the release.

Thanks!

**Comment by SaptakS** [comment]
Yeah, it's on my plate, just haven't been able to get around to it. Hopefully this week.

**Comment by SaptakS** [comment]
@emmapeel2 I have addressed the CI issues in this PR https://github.com/onionshare/onionshare/pull/1915. Once this is reviewed and merged, we can rebased (or merge) this branch with main to hopefully fix the CI issues and then we can get this merged.

**Review by SaptakS — APPROVED** [review]
CI now passing, and looks good to me. Merging

**Pull request merged**
