### PR TITLE
Switch Settings and Tor Settings dialogs into tabs

### LINKED ISSUE #661: Fetch bridges for the user
TorProject just added a feature into tor launcher.
```
to allow automated retrieval of bridges using Moat, a BridgeDB service which works
over a meek transport and requires the user to solve a CAPTCHA to
obtain bridges.
```
bridge

**I wonder if this would be useful for onionshare, the ability to retrieve unblocked obfs4 bridges using meek. Large adversaries "China" may block the bundled obfs4 bridges.** 
https://gitweb.torproject.org/tor-launcher.git/commit/?id=e921bb15681ac54c9e937b564d31a2a6ec2ceb33
@mig5

### LINKED ISSUE #1442: Support snowflake bridges, and update bridge selection UI
We need to add support for snowflake bridge (source code [here](https://gitweb.torproject.org/pluggable-transports/snowflake.git)), and we should also update our UI to look like Tor Browser's UI:

Screenshot from 2021-10-11 19-47-17
Screenshot from 2021-10-11 19-47-42

While not necessary, if it turns out to not be too much work it would be cool to support "Request a bridge from torproject.org" as well:

Screenshot from 2021-10-11 19-47-56
Screenshot from 2021-10-11 19-48-10

Right now during development in Linux we tell users to install `tor` and `obfs4proxy` from their package manager, but `snowflake` isn't widely packaged. So this issue will involve making a `get-tor-linux.py` that downloads the linux Tor Browser and extracts binaries, including `snowflake-client` (which is in `tor-browser_en-US/Browser/TorBrowser/Tor/PluggableTransports/snowflake-client`), for development. And then we'll build snowflake from source for Flatpak and Snapcraft.

### PR DESCRIPTION
**Pull request by micahflee**
Fixes #661
Fixes #1442

This implements the "Make TorSettingsDialog and SettingsDialog tabs instead of modal dialogs" part of #1442.

When you click the tor icon in the the corner, Tor Settings opens as a tab:

Screenshot from 2021-10-24 19-34-00

And when you click the gear icon in the corner, Settings opens as a tab:

Screenshot from 2021-10-24 19-34-30

Because the Tor Settings is now a tab and we're working within a minimum width and height, I totally changed around the layout. Also made is so when you click "Test Connection to Tor", or if you click Save and it requires reconnecting to tor, it does the connection directly in the tab, rather than in a separate TorConnectionDialog:

Screenshot from 2021-10-24 19-36-28

When testing, it still pops up the success status in a separate alert dialog:

Screenshot from 2021-10-24 19-36-42

When there's an error, it also shows the error directly in the tab, rather than in an alert dialog:

Screenshot from 2021-10-24 19-37-33

One thing that is _not implemented_ in this PR is this workflow:
- Open OnionShare, before it finishes connecting to Tor click Cancel
- It asks if you want to open settings or to quit. Open Settings
- Then just close the settings tab without changing anything

Before, this would quit OnionShare with an error saying that you couldn't connect to Tor so OnionShare can't start. Now, it just closes the tab and leaves OnionShare in a kinda broken state, where Tor isn't connected but you can still try to start services, etc. I think though that rather than fixing this here, this is better to address in #1439 since it will be totally tied into whatever the quickstart screen will look like.

### CODE REVIEW

**Comment by mig5** [comment]
> We maybe need to hide the primary nav and 'Ready to share' if the Tor connection widget is still reconnecting in the Tor Settings tab.

Another way to solve the problem - we can make all other tabs 'disabled' whilst the TorSettingsTab is open. And re-enable them when it is closed again.

A bit brutal but it does solve the problem

```
diff --git a/desktop/src/onionshare/tab_widget.py b/desktop/src/onionshare/tab_widget.py
index da7d50bf..fceb4adf 100644
--- a/desktop/src/onionshare/tab_widget.py
+++ b/desktop/src/onionshare/tab_widget.py
@@ -230,6 +230,10 @@ class TabWidget(QtWidgets.QTabWidget):
             if type(self.tabs[tab_id]) is TorSettingsTab:
                 self.setCurrentIndex(self.indexOf(self.tabs[tab_id]))
                 return
+            else:
+                # Disable the other tabs whilst the TorSettingsTab is open
+                self.common.log("TabWidget", "open_tor_settings_tab", f"Disabling tab ID {tab_id}")
+                self.setTabEnabled(tab_id, False)
 
         self.tor_settings_tab = TorSettingsTab(
             self.common, self.current_tab_id, self.are_tabs_active()
@@ -312,6 +316,10 @@ class TabWidget(QtWidgets.QTabWidget):
             self.common.log("TabWidget", "closing a settings tab")
 
             if type(self.tabs[tab_id]) is TorSettingsTab:
+                # Re-enable all other tabs
+                for other_tab_id in self.tabs:
+                    self.common.log("TabWidget", "close_tab", f"Re-enabling tab ID {other_tab_id}")
+                    self.setTabEnabled(other_tab_id, True)
                 self.tor_settings_tab = None
 
             # Remove the tab
```

**Comment by micahflee** [comment]
Ok I think this fixes the remaining issues. @mig5 I applied your patch and seems to work.

And I also editing the `Mode` object which all modes (`ShareMode`, etc) inherit from to display a generic "OnionShare is not connected to the Tor network" when tor isn't connected, and when tor is connected it shows the actual mode content.

Screenshot from 2021-11-06 20-08-43

An easy way to test is to open OnionShare and click cancel while Tor is first connecting. All of the modes now start out in the disconnected state (however, the new tab page still shows you a new tab and lets you pick a mode). Then if you go to Tor Settings and select some settings that work and connect successfully, all the Modes switch to start showing content.

**Comment by micahflee** [comment]
I just made sure this all works in Windows and macOS too, which solves these parts of #1442 as well:

- Update tor binaries stuff to work in Windows, macOS
- Make sure check for update in Settings dialog still works in Windows, macOS

**Comment by micahflee** [comment]
Now this PR will completely resolve #1442

**Comment by mig5** [comment]
This is looking pretty good.

I confirm when I 'cancel' the Tor connection dialog, an *existing* tab shows the 'OnionShare is not connected to the Tor network' message and I can't interact with it.

But if I go to the Tor Settings tab and change a bridge mode and click save and it starts connecting to Tor, and meanwhile, I open a *new* tab and choose a Mode for it, and Tor is still not connected, I'm able to see all the settings for the new Mode's tab, including clicking Start, and it of course fails as I'm not fully connected to Tor. 

I get this in the debug - you can see where I start a Receive Mode tab and click Start, whilst the 'Connecting to Tor' is still at 95%

```
Connecting to the Tor network: 62% - Loading relay descriptors[Nov 08 2021 11:51:36 AM] TabWidget.add_tab: mode_settings: None
[Nov 08 2021 11:51:36 AM] Tab.__init__
[Nov 08 2021 11:51:36 AM] OnionShare.__init__
[Nov 08 2021 11:51:36 AM] TabWidget.tab_changed: Tab was changed to 2
[Nov 08 2021 11:51:36 AM] Common.get_resource_path: filename=wordlist.txt
[Nov 08 2021 11:51:36 AM] Common.get_resource_path: filename=wordlist.txt, path=/home/user/git/onionshare/desktop/venv/lib/python3.7/site-packages/onionshare_cli/resources/wordlist.txt
[Nov 08 2021 11:51:36 AM] ModeSettings.load: creating /home/user/.config/onionshare/persistent/putt-gristle-sharper.json
[Nov 08 2021 11:51:36 AM] TabWidget.change_persistent: tab_id: 2, is_persistent: False
[Nov 08 2021 11:51:36 AM] MainWindow.bring_to_front
Connecting to the Tor network: 77% - Connected to pluggable transport to build circuits[Nov 08 2021 11:51:37 AM] Tab.receive_mode_clicked
[Nov 08 2021 11:51:37 AM] Web.__init__: is_gui=True, mode=receive
[Nov 08 2021 11:51:37 AM] Common.get_resource_path: filename=static
[Nov 08 2021 11:51:37 AM] Common.get_resource_path: filename=static, path=/home/user/git/onionshare/desktop/venv/lib/python3.7/site-packages/onionshare_cli/resources/static
[Nov 08 2021 11:51:37 AM] Common.get_resource_path: filename=templates
[Nov 08 2021 11:51:37 AM] Common.get_resource_path: filename=templates, path=/home/user/git/onionshare/desktop/venv/lib/python3.7/site-packages/onionshare_cli/resources/templates
[Nov 08 2021 11:51:37 AM] Web.generate_static_url_path: new static_url_path is /static_s65kmdmcqegspqi7xorbbfykha
[Nov 08 2021 11:51:37 AM] ReceiveModeWeb.__init__
[Nov 08 2021 11:51:37 AM] ServerStatus.update
[Nov 08 2021 11:51:37 AM] ServerStatus.update
Connecting to the Tor network: 95% - Establishing a Tor circuit[Nov 08 2021 11:51:39 AM] ServerStatus.update
[Nov 08 2021 11:51:39 AM] Mode.start_server
[Nov 08 2021 11:51:39 AM] Onion.get_tor_socks_port
Traceback (most recent call last):
  File "/home/user/git/onionshare/desktop/src/onionshare/tab/mode/__init__.py", line 278, in start_server
    self.start_onion_thread()
  File "/home/user/git/onionshare/desktop/src/onionshare/tab/mode/__init__.py", line 285, in start_onion_thread
    and not self.app.onion.supports_stealth
AttributeError: 'Onion' object has no attribute 'supports_stealth'
Connecting to the Tor network: 100% - Done
[Nov 08 2021 11:51:39 AM] Onion.connect: Connected to tor 0.4.7.1-alpha (git-ecb91e75e4770fa7)
[Nov 08 2021 11:51:40 AM] TorConnectionWidget._connected_to_tor
[Nov 08 2021 11:51:40 AM] TabWidget.close_tor_settings_tab
[Nov 08 2021 11:51:40 AM] TabWidget.close_tab: 1
[Nov 08 2021 11:51:40 AM] TabWidget.closing a settings tab
[Nov 08 2021 11:51:40 AM] TabWidget.tab_changed: Tab was changed to 2
```

So somehow this isn't surfacing as expected in the Tab's `__init__` constructor, though it looks like it ought to...

Everything else looks good though, like if I change the Tor bridge mode and all *existing* tabs correctly hide their output until Tor successfully reconnects.

I also tested the moat/meek/bridgeDB functionality on macOS, and it's working great.

**Comment by mig5** [comment]
Also, we may want to deny access to the 'Check for New Version' button whilst Tor is reconnecting.. should SettingsTab also 'hide' its settings whilst Tor is not connected? Maybe that's a bit too heavy-handed?

**Comment by micahflee** [comment]
I have fixed the problem where when you start reconnecting to Tor and quickly open a new tab, it thinks you're already connected. Now it doesn't think you're connected until Tor successfully connects.

And I also just made the 'Check for Updates' button in the Settings tab hide when Tor is disconnected, and show again when it's connected.

**Review by mig5 — APPROVED** [review]
It's working great! I think this can be merged in now.

**Pull request merged**
